name: "Test"
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      CLARIFAI_PAT: ${{ secrets.CLARIFAI_PAT }}

    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: "Install Deps"
        run: bun install
      - name: "Test"
        run: bun vitest --coverage.enabled true
      - name: "Report Coverage"
        # Set if: always() to also generate the report if tests are failing
        # Only works if you set `reportOnFailure: true` in your vite config as specified above
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
